sudo: required

services:
  - docker

stages:
  - build

before_script:
  - whoami
  - docker version
  - cat /proc/version
  - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin

script:
  - date

  - docker build -t "$REGISTRY_USER/steam1" build/ --build-arg IMAGE=ubuntu:16.04
  - date
  - docker images
  - docker push "$REGISTRY_USER/steam1"
  - date

  - docker build -t "$REGISTRY_USER/game1" build2/ --build-arg "IMAGE=$REGISTRY_USER/steam1"
  - date
  - docker images
  - docker push "$REGISTRY_USER/game1"
  - date

  #- docker pull alpine
  #- docker tag alpine $REGISTRY_USER/alpine2:test
  #- docker push $REGISTRY_USER/alpine2:test
  #- docker build -t ubuntu:test build/ --build-arg IMAGE=ubuntu:16.04
  #- docker run --name testcontainer ubuntu:test /bin/sh -c "steamcmd.sh +login anonymous +force_install_dir /app +app_update 222860 validate +quit"
  #- docker images

after_script:
  - docker logout