services:
  - docker

env:
  matrix:
    - TEST_IMAGE=sourceservers/hl2mp:latest COMMAND="printenv && ls -al && exec srcds_linux -game hl2mp +version +exit"
    - TEST_IMAGE=goldsourceservers/valve:latest COMMAND="printenv && ls -al && exec hlds_linux -game valve +version +exit"

before_script:
  - whoami
  - docker version
  - cat /proc/version
  - df -h

script:
  - echo $TEST_IMAGE
  - echo $COMMAND
  - docker run -t --rm "${TEST_IMAGE}" "${COMMAND}"
  - docker run --rm "${TEST_IMAGE}" "${COMMAND}"

after_script:
  - date