sudo: required

services:
  - docker

stages:
  - build

before_script:
  - whoami
  - docker version

script:
  - date
  - docker images
  - docker build -t image:test build/
  - docker run -it image:test /bin/sh -c "pwd && ls -al"

after_install:
  - date