services:
  - docker

env:
  global:
    - VAR1=var1
    - VAR2=var2

before_script:
  - whoami
  - docker version
  - cat /proc/version
  - df -h
  #- echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin

script:
  - date
  - echo $VAR1
  - echo $VAR2
  - echo $VAR_API

after_script:
  #- docker logout