sudo: required

services:
  - docker

stages:
  - build

before_script:
  - whoami
  - docker version
  - cat /proc/version

script:
  - date 
  - docker build -t ubuntu:test build/ --build-arg IMAGE=ubuntu:16.04
  - docker run ubuntu:test /bin/sh -c "pwd && ls -al"
  - docker images

  - docker build -t debian:test build/ --build-arg IMAGE=debian:jessie
  - docker run debian:test /bin/sh -c "pwd && ls -al"
  - docker images

  - date

after_script:
  - date