language: bash
services:
  - docker

# stages:
#   - build
#   - test

env:
  global:
    - g_VAR=g_value
  matrix:
    - m_VAR=m_value1
    - m_VAR=m_value2
    - m_VAR=m_value3

before_script:
  - whoami
  - cat /etc/*release
  - df -h
  - free
  #- echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin
  - docker images

script:
  - date
  - echo $TRAVIS_BUILD_STAGE_NAME
  - echo $g_VAR
  - echo $m_VAR

jobs:
  include:
    - stage: stage1
      script:
        - date
        - echo $TRAVIS_BUILD_STAGE_NAME
    - stage: stage2
      script:
        - date
        - echo $TRAVIS_BUILD_STAGE_NAME

after_script:
  - echo after script
  #- docker logout