dist: xenial

services:
  - docker

env:
  matrix:
    #- TEST_IMAGE=sourceservers/hl2mp COMMAND="printenv && ls -al && exec srcds_linux -game hl2mp +version +exit"
    - TEST_IMAGE=alpine:latest COMMAND="ls"
    - TEST_IMAGE=alpine:latest COMMAND="ls -al"
    - TEST_IMAGE=alpine:latest COMMAND="printenv && ls -al"

before_script:
  - whoami
  - docker version
  - cat /proc/version
  - df -h

script:
  - echo $TEST_IMAGE
  - echo $COMMAND
  - docker run "${TEST_IMAGE}" sh -c "${COMMAND}"

after_script:
  - date