language: minimal
dist: xenial
services:
  - docker

env:
  global:
    - g_VAR="g_value"
  matrix:
    - m_VAR="m_value1"
    # - m_VAR="m_value2"
    # - m_VAR="m_value3"

before_script:
  - |
    hostname
    whoami
    cat /etc/*release
    lscpu
    free
    df -h
    docker info
    docker version

script:
  - |
    i=0; while true; do
        echo "Iteration $(( $i+1 )): $(date)"
        dd if=/dev/zero of="tempfile.$i" bs=1M count=1024
        ls -al "tempfile.$i"
        df -h
        i=$((i + 1))
        echo
        sleep 1
    done
