#sudo: required
language: bash
services:
  - docker

env:
  global:
    - g_var=globalvalue
  matrix: 
    - foo=1 bar=2
    #- foo=3 bar=4

stages:
  - build

before_script:
  - whoami
  - docker version
  - cat /proc/version
  - df -h
  - free
  #- echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin

script:
  - echo $g_var
  - echo $foo && echo $bar

  #- docker build -t "$REGISTRY_USER/csgotest" build2/
  #- docker images
  #- travis_wait 20 docker push "$REGISTRY_USER/gametest"
  #- date

  - REGISTRY_ORG='goldsourceservers'
  - docker pull alpine
  - docker tag alpine $REGISTRY_USER/alpine2:test
  - docker push $REGISTRY_ORG/alpine2:test

after_script:
  - docker logout