language: shell
dist: xenial
services:
  - docker
# branches:
#   except:
#    - /.*/

# stages:
#   - build
#   - test

env:
  global:
    - g_VAR="g_value"
  matrix:
    - m_VAR="m_value1"
    # - m_VAR="m_value2"
    # - m_VAR="m_value3"

before_script:
  - |
    hostname
    whoami
    cat /etc/*release
    lscpu
    free
    df -h
    docker info
    docker version

  #- echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin

  - set -e

script:
  - |
    travis_wait 20 sleep 15m
  - date
  - echo $TRAVIS_BUILD_STAGE_NAME
  - echo $g_VAR
  - echo $m_VAR
  # - docker images

# jobs:
#   include:
#     - stage: stage1
#       script:
#         - date
#         - echo $TRAVIS_BUILD_STAGE_NAME
#     - stage: stage2
#       script:
#         - date
#         - echo $TRAVIS_BUILD_STAGE_NAME

# after_script:
#   - echo after script
#   #- docker logout
