dist: xenial

services:
  - docker

env:
  global:
    - test=1
    - BAR="test2
    - BAZ=test3
    
before_script:
  - whoami
  - docker version
  - cat /proc/version
  - df -h
  #- echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin

script:
  - date
  - echo $TESTVAR
  - echo $TESTVAR2
  - echo $test
  - echo $BAR
  - echo $BAZ

after_script:
  #- docker logout