sudo: required

services:
  - docker

stages:
  - build

before_script:
  - whoami
  - docker version

script:
  - date 
  - docker images
  - docker build -t ubuntu:test build/
  - docker run image:test /bin/sh -c "pwd && ls -al"
  - docker pull debian
  - docker build -t debian:test build/
  - docker run debian:test /bin/sh -c "pwd && ls -al"
    - docker images

after_script:
  - date