dist: xenial

services:
  - docker

env:
  matrix:
    - TEST_IMAGE=sourceservers/hl2mp command="printenv && ls -al && exec srcds_linux -game hl2mp +version +exit"

before_script:
  - whoami
  - docker version
  - cat /proc/version
  - df -h

script:
  - echo $TEST_IMAGE
  - echo $command
  #- docker run "${TEST_IMAGE}" sh -c "${command}"

after_script:
  - date