dist: xenial

services:
  - docker

env:
  global:
    - GAME_BIN="srcds/"
    - GAME="h2mp/"
  matrix:
    - TEST_IMAGE=sourceservers/hl2mp command="printenv && ls -al && exec ${GAME_BIN} -game ${GAME} +version +exit"
    
before_script:
  - whoami
  - docker version
  - cat /proc/version
  - df -h
  #- echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin

script:
  -  echo $TEST_IMAGE
  -  echo $command

after_script:
  #- docker logout