language: bash

env:
  global:
    - GLOBAL_VAR1="global1"
  matrix:
    - MATRIX_VAR1="matrix1_1"
    - MATRIX_VAR1="matrix1_2"
    - MATRIX_VAR1="matrix1_3"
    - MATRIX_VAR1="matrix1_4"
    - MATRIX_VAR1="matrix1_5"
    - MATRIX_VAR1="matrix1_6"
    - MATRIX_VAR1="matrix1_7"
    - MATRIX_VAR1="matrix1_8"
    - MATRIX_VAR1="matrix1_9"
    - MATRIX_VAR1="matrix1_10"

before_script:
  - whoami
  - cat /etc/*release
  - lscpu
  - df -h
  - free

script:
  - date
  - echo $GLOBAL_VAR1
  - echo $MATRIX_VAR1
  - sleep 300