language: bash
services:
  - docker

stages:
  - build
  - test

env:
  global:
    - g_VAR=g_value
  matrix:
    - m_VAR=m_value1
    - m_VAR=m_value2
    - m_VAR=m_value3

before_script:
  - whoami
  - cat /etc/*release
  - df -h
  - free
  #- echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin
  - docker images

jobs:
  include:
    - stage: build
      script:
        - date
        - echo $g_VAR
        - echo $m_VAR
        - docker pull alpine
        - docker images
        - echo TRAVIS_BRANCH
    - stage: test
      script:
        - date
        - echo $g_VAR
        - echo $m_VAR
        - docker images
        - echo TRAVIS_BRANCH

after_script:
  - echo after script
  #- docker logout