sudo: required

services:
  - docker

stages:
  - build

before_script:
  - whoami
  - docker version
  - cat /proc/version
  - df -h
  - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin

script:
  - echo $TESTVAR
  - date

after_script:
  - docker logout